id: 2ed7eeb41f9044e5af61fafa917f0ad3
initial_creation_type: ocr
source_metadata:
  volumes:
    42b1d0a25ae444aa9c48719934b15cab:
      base_file: v066.txt
      image_group_id: I1PD95912
      title: ''
      total_pages: 1529
      volume_number: 67
